# -*- coding: utf-8 -*-
"""knn_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A0377OZvPQSAzh5hOBI1slDUDMfBDomN
"""

import numpy as np

# Original dataset
data = [
    [150, 7.0, 1, 'Apple'],
    [120, 6.5, 0, 'Banana'],
    [180, 7.5, 2, 'Orange'],
    [155, 7.2, 1, 'Apple'],
    [110, 6.0, 0, 'Banana'],
    [190, 7.8, 2, 'Orange'],
    [145, 7.1, 1, 'Apple'],
    [115, 6.3, 0, 'Banana']
]

# Step 1: Create label encoding dictionary
label_map = {
    'Apple': 0,
    'Banana': 1,
    'Orange': 2
}

# Step 2: Separate features (X) and labels (y)
X = []  # features
y = []  # labels

for row in data:
    X.append(row[:3])                 # first 3 values → features
    y.append(label_map[row[3]])       # last value → encoded label

# Convert to NumPy arrays
X = np.array(X)
y = np.array(y)

# Print results
print("Feature Matrix (X):\n", X)
print("\nLabel Vector (y):\n", y)

# Step 2: Euclidean Distance Function
def euclidean_distance(p1, p2):

    # Convert to numpy arrays
    p1 = np.array(p1)
    p2 = np.array(p2)

    # Apply formula
    distance = np.sqrt(np.sum((p1 - p2) ** 2))

    return distance

class KNN:

    # Constructor
    def __init__(self, k=3):
      self.k = k
      self.X_train = None
      self.y_train = None

    # Store training data
    def fit(self, X, y):
        self.X_train = X
        self.y_train = y

    # Euclidean distance function
    def euclidean_distance(self, p1, p2):
        return np.sqrt(np.sum((p1 - p2) ** 2))

    # Predict for a single point
    def predict_one(self, x):

        distances = []

        # Step 1: Compute distance from x to all training points
        for i in range(len(self.X_train)):
            dist = self.euclidean_distance(x, self.X_train[i])
            distances.append((dist, self.y_train[i]))

        # Step 2: Sort based on distance
        distances.sort(key=lambda d: d[0])

        # Step 3: Take first k neighbors
        k_neighbors = distances[:self.k]

        # Step 4: Extract labels of neighbors
        labels = [label for (_, label) in k_neighbors]

        # Step 5: Majority voting
        counts = np.bincount(labels)   # count occurrences
        prediction = np.argmax(counts) # label with max count

        return prediction

    # Predict for multiple test points
    def predict(self, X_test):
        predictions = []

        for x in X_test:
            pred = self.predict_one(x)
            predictions.append(pred)

        return np.array(predictions)

# Test data
test_data = np.array([
    [118, 6.2, 0],  # Banana
    [160, 7.3, 1],  # Apple
    [185, 7.7, 2]   # Orange
])

reverse_map = {
    0:'Apple',
    1:'Banana',
    2:'Orange',
}

# Step 1: Create KNN model
knn = KNN(k=3)

# Step 2: Fit (store training data)
knn.fit(X, y)

# Step 3: Predict
predictions = knn.predict(test_data)

# Print numeric predictions
print("Predicted Labels :")
for i in predictions:
    print(reverse_map[i])

# Expected labels (Banana=1, Apple=0, Orange=2)
expected = np.array([1, 0, 2])

# Accuracy function
def accuracy(y_true, y_pred):
    correct = np.sum(y_true == y_pred)
    return correct / len(y_true)

# Test different k values
k_values = [1, 3, 5]

for k in k_values:
    print("Testing with k =", k)

    # Create and train model
    knn = KNN(k=k)
    knn.fit(X, y)

    # Predict
    preds = knn.predict(test_data)

    # Accuracy
    acc = accuracy(expected, preds)

    # Decode predictions
    decoded_preds = [reverse_map[p] for p in preds]

    # Print results
    print("Predicted (encoded):", preds)
    print("Predicted (fruits):", decoded_preds)
    print("Expected:", ['Banana', 'Apple', 'Orange'])
    print("Accuracy:", acc)
    print("\n")

